services:
  api-zabbix:
    container_name: api_server_laravel
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile

    volumes:
      - ../:/var/www/html/

    ports:
      - 8001:80
    deploy:
      restart_policy:
        condition: on-failure
